version: "3.9"

networks:
  insurence:

services:
  message-broker:
    networks: [insurence]
    container_name: kafka-container
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  zookeeper:
    networks: [insurence]
    container_name: zookeeper-container
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-ui:
    networks: [insurence]
    container_name: kafka-ui-container
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8089:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-container:9092
    depends_on:
      - message-broker

  db:
    networks: [insurence]
    container_name: postgresql-container
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1984
      POSTGRES_DB: insurance-calculator-db
    ports:
      - "5433:5432"

  insurance-calculator-app:
    networks: [insurence]
    container_name: insurance-calc-container
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - message-broker
      - db
